config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
   resources :lists do
   resources :bookmarks, only: [:new, :create, :destroy]
   end
   resources :bookmarks, only: [:show] # to be checked

  # resources :movies, only: [:show] # to be checked

    # get '/lists', to: 'lists#index'
    # post '/lists', to: 'lists#create'
    # get '/lists/new', to: 'lists#new'
    # get '/lists/:id', to: 'lists#show'
    # get '/lists/:id/edit', to: 'lists#edit'
    # delete '/lists/:id', to: 'lists#destroy'

    # get '/lists/:list_id/bookmarks', to: 'bookmarks#new'
    # post '/lists/:list_id/bookmarks', to: 'bookmarks#create'
    # delete '/list/:list_id/bookmarks/:id', to: 'bookmarks#destroy'

    # get '/lists/:list_id/bookmarks/movies', to: 'movies#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(list_params)
    @bookmark.save
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    #redirect_to lists_path, status: :see_other
  end
end

private

def bookmarks_params
  params.require(:list).permit(:comment)
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

 # def show movie
  #   @list = List.find(params[:id])
  #   @movie = List.bookmarks.find(params[:id])
  # end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
  end
end

private

def list_params
  params.require(:list).permit(:name)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmark</h1>
<%= simple_form_for @bookmark do |f| %>
  <%= f.input :name %>
  <%= f.association :movie %>
  <%# <%= f.association :list % --not needed- that can be entered via params - address>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Movie List</h1>
<%# <%= simple_form_for @lists do |f| %>
  <ul>
  <% @lists.each do |list|  %>
  <%= list.name  %>


<% end %>

<%# <%= link_to "Create another list", list_path(@list)%>